AntiMicroX/antimicrox

README.md

PR connected with: https://github.com/AntiMicroX/antimicroX/issues/13

docs: remove outdated build instructions for arch

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Closes #8 
- add basic GH feature request/bugfix issue selector
- some basic PR template with some reminders

chore(github): update issue, PR templates

---

CMakeLists.txt
Changelog
README.md
other/appdata/io.github.antimicrox.antimicrox.appdata.xml.in

chore(release): 3.1.1

---

src/joybuttoncontextmenu.cpp

fix: wrong button assignment #7

---

README.md

docs: readme Fedora update

---

README.md

Closes #9 
- App is on Flathub, add installation instructions.

docs: add flatpak info to README

---

BUILDING.md
other/io.github.antimicrox.antimicrox.yml

For #9
Only minor docs cleanup.

docs: flatpak readme

---

src/advancebuttondialog.ui
src/axiseditdialog.ui
src/dpadeditdialog.ui
src/joycontrolstickeditdialog.ui
src/joytabwidget.cpp
src/mainsettingsdialog.ui

Ensures usage of default system icons also in `ui` files.

fix: Ensure usage of basic system icons in missed locations

---

CMakeLists.txt

Clearly defining our requirements will let us avoid some problems with compatibility.
Like here for example:  https://github.com/AppImage/appimage.github.io/pull/2074

fix: add requirements for QT and sdl version

---

CMakeLists.txt

Remove CMAKE_PREFIX_PATH entry #102

---

src/joybutton.cpp

fix: Not working Clear button

---

src/joybuttonslot.cpp

fix: Fix typo in logical statement

---

BUILDING.md

- mark CMake as not recommended way of installation ( Closes: #68 ) 
- Add simple instructions for building `rpm` packages

docs: update building and installation instructions

---

other/antimicrox.1

(only a band-aid; real fix would mean rewriting this in mdoc)
This is the same as https://github.com/AntiMicro/antimicro/pull/274

fix the manpage (hyphen as minus sign)

---

.github/workflows/release.yml
BUILDING.md
CMakeLists.txt
src/aboutdialog.cpp

Closes: #144
- describe flag ANTIMICROX_PKG_VERSION in docs
- integrate it with Cmake
- Update CI for building AppImage

docs: Integrate build markings 

---

README.md

Note: I am not the maintainer/packager.

Added openSUSE

---

README.md

Idea of @deoxal  
From https://github.com/AntiMicroX/antimicrox/issues/171

docs: Add information about commandline for flatpak packages

---

src/commandlineutility.cpp
src/joytabwidget.cpp

This may be useful with debugging https://github.com/AntiMicroX/antimicrox/issues/172

Add new logs associated with loading profile files

---

src/eventhandlers/uinputeventhandler.cpp
src/logger.cpp
src/logger.h
src/main.cpp

Small refactors

---

src/eventhandlerfactory.cpp

Switches from xtest to uinput when wayland session is detected
Part of issue #32

feat: switch from xtest to uinput when wayland is detected

---

src/event.cpp

Additional logs during execution of executables may be useful for debugging and troubleshooting purposes. Good example: https://github.com/AntiMicroX/antimicrox/issues/190

refactor: Refactor executing commands

---

BUILDING.md
CMakeLists.txt
other/Doxyfile_config.in

It will be good to later add it to our website https://github.com/AntiMicroX/antimicrox.github.io

docs: Create config for doxygen

---

src/joybutton.cpp
src/setjoystick.cpp

Addresses issues from https://github.com/AntiMicroX/antimicrox/issues/133

Other crash-related fixes

---

src/joytabwidget.cpp
src/logger.cpp
src/main.cpp

Additional logs

---

src/main.cpp

Closes https://github.com/AntiMicroX/antimicrox/issues/235
Basic handling of segfault and some minor refactors.

Segfault handling

---

.github/workflows/release.yml
BUILDING.md
CMakeLists.txt
src/logger.cpp
src/main.cpp

Closes #218 
Changes: 
- create config for debug build
- add printing stack trace in case of segfault
- add printing build type in logs

Debug build

---

CMakeLists.txt
src/main.cpp

Part of https://github.com/AntiMicroX/antimicrox/issues/237
Minor improvements for windows build linked with removing unnecessary differences between unix and windows build.

Windows build improvements

---

.github/workflows/main.yml

It will save some time and resources

ci: Disable build triggering on PR

---

.github/workflows/code_formatting.yml
.github/workflows/main.yml
.github/workflows/release.yml

- Add concurrency
- Add workflow dispatch
- Reformat for better readability
- Remove redundant lines
- Enable parallel builds
- Add pull request build
- Enable only master branch for CI
----
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>

 ci: Add concurrency and remove redundant lines

---

src/gui/mainwindow.cpp

Disable calibration for devices without joysticks

---

.github/workflows/static-code-analysis.yml

Closes #287 
- Add CodeQl analysis
- https://codeql.github.com/
- https://github.com/github/codeql
----
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>

ci: Add static code analysis

---

.github/workflows/code_formatting.yml
.github/workflows/static-code-analysis.yml

Fixes #289
- Adds infer
- remove parallel from builds
- Add name to code formatting workflow
----
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>

Add infer static code analysis to CI

---

src/commandlineutility.cpp
src/gui/mainsettingsdialog.cpp
src/gui/mainsettingsdialog.ui

Suggestion of description clarification: https://github.com/AntiMicroX/antimicrox/issues/301#issuecomment-981120987

Clarification of names and --profile flag description

---

src/gui/mainsettingsdialog.cpp

fix: Populate autoprofiles list on Windows

---

src/main.cpp

feat: Set theme for Windows

---

README.md
other/appdata/io.github.antimicrox.antimicrox.appdata.xml.in
src/gui/mainsettingsdialog.cpp

Note about lack of AutoProfile in Wayland

---

src/gui/joytabwidget.cpp
src/joybutton.cpp
src/uihelpers/joytabwidgethelper.cpp

Log improvements

---

src/joybutton.cpp
src/joybutton.h
src/joycontrolstick.cpp
src/joycontrolstick.h

Closes: https://github.com/AntiMicroX/antimicrox/issues/320

Memory fixes

---

src/main.cpp

chore: Update daemon launching

---

src/gui/buttoneditdialog.cpp
src/gui/quicksetdialog.cpp
src/joyaxis.cpp
src/joybutton.cpp
src/logger.cpp

chore: Simplify some logs

---

src/gui/mainsettingsdialog.cpp
src/gui/mainsettingsdialog.ui
src/gui/mainwindow.cpp
src/gui/mainwindow.h

Change way of notifying user about low battery level.

---

src/gui/mainwindow.cpp
src/resources.qrc

fix: Use colourful antimicrox icon in tray by default

---

src/logger.cpp

Windows missing characters in log files

---

.github/workflows/main.yml
.github/workflows/release.yml
src/event.cpp

Fix compatiblility with QT older than 5.10

---

CMakeLists.txt
share/LICENSE_SDL_GameControllerDB

chore: Add missing license for SDL_GameControllerDB

---

share/antimicrox/translations/antimicrox_es.ts

I have updated the Spanish translation, which was completely outdated.

Updated Spanish translation

---

src/autoprofileinfo.cpp
src/autoprofileinfo.h
src/gui/mainsettingsdialog.cpp

fix: Auto profile is not saved when exe path is not defined

---

src/gui/mainwindow.ui

Closes https://github.com/AntiMicroX/antimicrox/issues/422

chore: Remove unused "Game Controller Mapping" button

---

.github/workflows/main.yml
.github/workflows/release.yml

Downgrade sdl windows

---

.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/question.yaml

[skip ci]
- fix typo in label name
- add additional info in question template

chore: Update issue templates

---

.github/workflows/main.yml
src/gui/mainwindow.cpp

fix: Broken QT 5.9 compatibility

---

src/autoprofilewatcher.cpp
src/gui/flashbuttonwidget.cpp

Closes: https://github.com/AntiMicroX/antimicrox/issues/425  
Closes: https://github.com/AntiMicroX/antimicrox/issues/426

Fix deprecation Warnings

---

.gitignore
.vscode/extensions.json
.vscode/launch.json
.vscode/qt5.natvis.xml
.vscode/settings.json
.vscode/snippets.md

It would make work much easier for developers using Visual Studio Code

chore: include proper Visual Studio Code configs for developers

---

other/appdata/io.github.antimicrox.antimicrox.appdata.xml.in

-remove deprecated mimetype
-add bugtracker link
-update description (nested lists are not allowed)

docs: Update AppStream metadata

---

src/eventhandlers/baseeventhandler.cpp
src/eventhandlers/baseeventhandler.h
src/eventhandlers/uinputeventhandler.cpp
src/eventhandlers/uinputeventhandler.h
src/eventhandlers/winsendinputeventhandler.cpp
src/eventhandlers/winsendinputeventhandler.h
src/eventhandlers/xtesteventhandler.cpp
src/eventhandlers/xtesteventhandler.h

Closes: https://github.com/AntiMicroX/antimicrox/issues/501

fix: Broken spring mouse Event on Windows

---

src/inputdaemon.cpp
src/joyaxis.cpp
src/joybutton.cpp

- Remove the most spammy ones
- Add log showing currently precessed event
Linked with: #307

chore: Improve logs

---

.github/workflows/release.yml
CMakeLists.txt

- adds CMake option to compile with portability on Windows & package portable zip file
- adds portable zip file to releases workflow
Closes #343

Portable Windows Builds

---

src/gui/addeditautoprofiledialog.cpp
src/gui/addeditautoprofiledialog.h
src/winextras.cpp

Closes #586   
Closes https://github.com/AntiMicroX/antimicrox/issues/584

Autoprofile fixes

---

src/gui/addeditautoprofiledialog.cpp

fix: Fix loading window name on Windows

---

src/gui/advancebuttondialog.cpp
src/sdleventreader.cpp

Linked with: https://github.com/AntiMicroX/antimicrox/issues/524

Fix insert warning

---

src/gui/addeditautoprofiledialog.cpp
src/gui/addeditautoprofiledialog.h

Closes https://github.com/AntiMicroX/antimicrox/issues/585

fix: Remove disabling Auto-profile title box

---

src/gamecontroller/gamecontroller.cpp
src/gamecontroller/gamecontroller.h
src/inputdaemon.cpp

fix: Always initialize Controller sensors when available

---

src/gui/advancebuttondialog.ui
src/gui/buttoneditdialog.cpp
src/gui/buttoneditdialog.h

Come cleanups in class ButtonEditDialog
Linked with: https://github.com/AntiMicroX/antimicrox/issues/529

Buttonedit cleanups

---

src/gui/buttoneditdialog.cpp
src/gui/buttoneditdialog.h
src/gui/buttoneditdialog.ui

feat: Add checkbox enabling numeric keypad in ButtonEditDialog

---

src/gui/advancebuttondialog.cpp
src/gui/advancestickassignmentdialog.cpp
src/inputdevice.cpp
src/inputdevice.h
src/xml/inputdevicexml.cpp

Closes: https://github.com/AntiMicroX/antimicrox/issues/655

fix: Invalid way of iterating through unordered list

---

src/eventhandlers/baseeventhandler.h
src/eventhandlers/uinputeventhandler.h

Created during the investigation of https://github.com/AntiMicroX/antimicrox/issues/521

docs: Better describe event code

---

src/joybuttonslot.cpp

Linked with: https://github.com/AntiMicroX/antimicrox/issues/554
ChatGPT works well.

Simplify constructors used by JoyButtonSlot to avoid code repetition

---

src/eventhandlers/uinputeventhandler.cpp

Closes: https://github.com/AntiMicroX/antimicrox/issues/521

fix: Fix uinput initialization for absolute mouse movement

---

src/gui/mainsettingsdialog.ui

chore: Add note with link to Weblate

---

src/event.cpp

fix: Don't execute every .sh file as bash script

---

CONTRIBUTING.md
README.md

docs: Write contributing guide

---

src/gui/addeditautoprofiledialog.cpp
src/gui/addeditautoprofiledialog.h

Closes: https://github.com/AntiMicroX/antimicrox/issues/727

fix: Fix and refactor adding default autoprofile

---

BUILDING.md

[skip ci]
Closes #...
- 
- 
- 
----

docs: add ninja-build to debian list of packages

---

.github/workflows/main.yml
.github/workflows/release.yml

This release contains fixes for: https://github.com/AntiMicroX/antimicrox/issues/663

chore: Bump SDL version

---

.github/ISSUE_TEMPLATE/feature_request.yaml

docs: Inform about thumbs up in enchancement template

docs: Inform about thumbs up in enchancement template

---

src/common.cpp
src/event.cpp
src/simplekeygrabberbutton.cpp

Fixes deprecations mentioned in #446

Fix deprecations in Qt

---

src/common.cpp
src/dpadcontextmenu.h
src/gamecontroller/gamecontroller.cpp
src/globalvariables.h
src/gui/joytabwidget.cpp
src/joyaxiscontextmenu.cpp
src/joybuttoncontextmenu.h
src/logger.h

Refactors for qt6

---

src/common.cpp
src/common.h
src/main.cpp

Fix deprecations

---

other/appdata/io.github.antimicrox.antimicrox.appdata.xml.in

- regenerate with jdAppStreamEdit
- Add missing developer name
Related with: https://github.com/flathub/io.github.antimicrox.antimicrox/pull/23#issuecomment-1994133124
(Some things were missing in appdata)

chore: Update Appstream appdata

---

CMakeLists.txt

refactor: Simplify and make finding QT more universal

---

CMakeLists.txt
share/antimicrox/translations/CMakeLists.txt

chore: Add support for QT6

---

src/logger.h

Linked with: https://github.com/AntiMicroX/antimicrox/issues/446

chore: Remove unused type from logger

---

src/gui/mainsettingsdialog.cpp
src/gui/mainwindow.cpp
src/winextras.cpp

Maintaining Windows XP support does not make sense anymore.

chore: Drop Windows XP support

---

src/logger.cpp
src/winextras.cpp

fix: Problems with legacy windows char conversions

---

README.md

[skip ci]
Closes #...
- 
- 
- 
----

docs: Note about polar

---

CMakeLists.txt

chore: Change minimal QT requirement to 5.10

---

src/gui/gamecontrollermappingdialog.cpp
src/gui/joysensoreditdialog.ui

Closes: #1003 
Adds log for: #985

Minor updates

---

src/gui/advancebuttondialog.cpp

Auto Reset Cycle After, fix #1002

---

src/gui/mainsettingsdialog.cpp
src/gui/mainsettingsdialog.ui

Simple note explaining Auto Profiles introduced to avoid misunderstandings like: https://github.com/AntiMicroX/antimicrox/issues/936

Update autoprofile info

---

src/inputdaemon.cpp

Closes: https://github.com/AntiMicroX/antimicrox/issues/562

chore: Remove unused code linked with USE_NEW_REFRESH

---

src/commandlineutility.cpp

Closes: https://github.com/AntiMicroX/antimicrox/issues/189

feat: Re-enable next option

---

src/joyaccelerometersensor.cpp

Hey @pktiuk!
Fixes build error here: https://koji.fedoraproject.org/koji/taskinfo?taskID=127932100 F42 is coming, and probably there are some C++ standard library changes. You can find the full F42 changelist here: https://fedoraproject.org/wiki/Releases/42/ChangeSet#GNU_Toolchain_Update_(gcc_15,_binutils_2.44,_glibc_2.41,_gdb_15+)
Don't rush for a new release, I'm adding a patch to the RPM package for now. :)
[Good Koji build](https://koji.fedoraproject.org/koji/taskinfo?taskID=128541299)

Fix Fedora 42 build

---

src/gui/aboutdialog.ui

- change copyright 2013 - 2022 to copyright 2013 - 2025
----

change copyright 2013 - 2022 to copyright 2013 - 2025
