- README.md
Related issue: https://github.com/AntiMicroX/antimicroX/issues/14
> Fix link in readme pointing to antimicroX-profiles

- src/setnamesdialog.cpp
Closes #6 
Method `QList<T> QHash::values() const` was returning list containing sets in random order.
From QHash [docs](https://doc.qt.io/qt-5/qhash.html#values):
> Returns a list containing all the values in the hash, in an **arbitrary** order. If a key is associated with multiple values, all of its values will be in the list, and not just the most recently inserted one.
> fix: Fix converting hash dictionary to random list. issue #6

- src/common.cpp
- src/common.h
- src/joytabwidget.cpp
- src/keyboard/virtualkeyboardmousewidget.cpp
- src/main.cpp
- src/mainsettingsdialog.cpp
- src/mainwindow.cpp
Part of #61 
Fix #56
It should also help with #58 
- Usage of default (provided by system) icons in place of all icons with existing counterparts.
> Fix: Use system icons in common cases to avoid incompatibility issues

- CMakeLists.txt
- src/gamecontroller/xml/gamecontrollerdpadxml.h
- src/xml/joydpadxml.cpp
- src/xml/joydpadxml.h
Closes #80 
Fixes linking error caused by improper compilation inclusion of `joydpadxml.cpp`.
> fix: fix linking error on armv7hl

- src/aboutdialog.cpp
- src/aboutdialog.ui
- tests/testaboutdialog.cpp
Based on idea from: https://github.com/AntiMicroX/antimicrox/pull/83
Could anyone having QT in version at least 5.14 How it looks?
Now changelog should look like this:
> style: Use Markdown for changelog

- BUILDING.md
1- someone just building might not know g++ is in gcc
2- on arch linux libqt5x11extras5-dev is named [qt5-x11extras](https://www.archlinux.org/packages/extra/x86_64/qt5-x11extras/)
> BUILDING.md: correct names for a couple of packages

- CMakeLists.txt
- other/CMakeLists.txt
- other/appdata/CMakeLists.txt
- share/antimicrox/translations/CMakeLists.txt
- tests/CMakeLists.txt
1- reformated them using CLion 
2- cleaned up some redundant code too.
and 
`find_package(SDL2 REQUIRED)` won't work on all systems, so I added it as a comment.
and the fix will be:
```
if(NOT DEFINED SDL2_LIBRARIES)
set(SDL2_LIBRARIES SDL2::SDL2)
endif ()
```
> refactor: clean up CMakeLists.txt files

- CMakeLists.txt
According to lintian this should be fixed:
```
E: antimicrox: no-copyright-file
W: antimicrox: desktop-mime-but-no-exec-code usr/share/applications/io.github.antimicrox.antimicrox.desktop
W: antimicrox: extended-description-line-too-long
W: antimicrox: non-standard-dir-perm usr/ 0775 != 0755
W: antimicrox: non-standard-dir-perm usr/bin/ 0775 != 0755
W: antimicrox: non-standard-dir-perm usr/include/ 0775 != 0755
W: antimicrox: non-standard-dir-perm ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: antimicrox: syntax-error-in-debian-changelog line 10 "badly formatted heading line"
W: antimicrox: syntax-error-in-debian-changelog line 102 "badly formatted heading line"
W: antimicrox: syntax-error-in-debian-changelog line 108 "badly formatted heading line"
W: antimicrox: …
```
> Rename changelog for deb packages

- src/common.h
- src/main.cpp
Closes #86 
- clean up migration logic a bit
- add `antimicro` migration
- `antimicro` takes priority over `antimicroX` (it's unlikely that a user will have both)
----
> feat: antimicro config migration

- other/io.github.antimicrox.antimicrox.xml
- Remove the `xml:lang` attribute from the `<comment>` element, as it causes systems to not display *any* comment in locales other than “en”, which is worse that displaying a generic english comment in such locales.
- Make `application/x-amgp` a subclass of `application/xml` so it is automatically associated with XML editors and the `application-xml` icon.
> feat: improve mime type definition

- other/appdata/io.github.antimicrox.antimicrox.appdata.xml.in
“appstreamcli validate” marks:
- summary must not end with a full stop
- bad HTML (nesting): `ul` may not be nested within `p`, both are block elements
> fix appdata formatting

- src/aboutdialog.cpp
By default, the date and time of the build are embedded into the binary as sort of origin/version/etc. marker. This is not, however, reproducible. This patch makes it so that packagers can define a præprocessor macro, `ANTIMICROX_PKG_VERSION`, to a C string which is then used instead; if this macro is not defined nothing changes.
The diff comes from [Debian](https://github.com/AntiMicroX/antimicrox/issues/87); by upstreaming the new string can be translated.
Example use: add `-DANTIMICROX_PKG_VERSION=\"'3.1.4-1 (Debian sid/amd64)'\"` to `CPPFLAGS`. Check the Hel̲p → A̲bout dialogue, tab Info, second line, to see its effect.
> make it possible to build reproducibly

- src/commandlineutility.cpp
- src/commandlineutility.h
- src/main.cpp
This one is meant to clean up a bit way of parsing arguments
Things do to:
> Refactor arguments parsing

- src/advancebuttondialog.cpp
- src/antimicrosettings.cpp
- src/antimicrosettings.h
- src/applaunchhelper.cpp
- src/autoprofilewatcher.cpp
- src/event.cpp
- src/gamecontrollermappingdialog.cpp
- src/inputdaemon.cpp
- src/joytabwidget.cpp
- src/keyboard/virtualkeypushbutton.cpp
- src/localantimicroserver.cpp
- src/logger.cpp
- src/logger.h
- src/main.cpp
- src/mainsettingsdialog.ui
- src/mainwindow.cpp
- src/x11extras.cpp
Closes #177   
Closes https://github.com/AntiMicroX/antimicrox/issues/78
> Rewrite logging system

- src/logger.h
> fix: remove unnecessary StreamPrinter operator using QStringView

- BUILDING.md
- CMakeLists.txt
- README.md
- other/40-uinput.rules
- other/60-antimcrox-uinput.rules
Closes: #32 
Allow non-root users to use event generation method based on uinput without root privileges.
> Allow regular users using uinput

- src/gamecontroller/gamecontroller.h
- src/inputdaemon.cpp
- src/inputdaemon.h
- src/inputdevice.cpp
- src/inputdevice.h
- src/joyaxis.h
- src/joybutton.h
- src/joybuttontypes/joycontrolstickbutton.h
- src/joybuttontypes/joycontrolstickmodifierbutton.h
- src/joycontrolstick.cpp
- src/joycontrolstick.h
- src/joydpad.h
- src/joystick.h
- src/main.cpp
- src/setjoystick.cpp
- src/setjoystick.h
- src/vdpad.cpp
- src/vdpad.h
There are many problems with destructors and deleting objects introduced during attempts of removing leaks.  
Some objects are deleted multiple times, or deleted in wrong threads etc.
This PR tackles some issues from https://github.com/AntiMicroX/antimicrox/issues/133
> Destructor fixes

- src/autoprofileinfo.h
- src/autoprofilewatcher.cpp
- src/calibration.cpp
- src/eventhandlerfactory.cpp
- src/eventhandlerfactory.h
- src/gamecontroller/gamecontrollertrigger.cpp
- src/inputdaemon.cpp
- src/inputdevicebitarraystatus.h
- src/joybutton.cpp
- src/joybuttontypes/joyaxisbutton.h
- src/joybuttontypes/joydpadbutton.h
- src/joybuttontypes/joygradientbutton.h
- src/joycontrolstick.cpp
- src/joydpad.cpp
- src/joydpad.h
- src/joytabwidget.cpp
- src/main.cpp
- src/mainsettingsdialog.cpp
- src/mainwindow.cpp
- src/setjoystick.cpp
- src/xml/joyaxisxml.cpp
- src/xml/joybuttonxml.cpp
Closes #76    
And addresses issues from: #133 
- Multiple fixes improving memory management and ensuring proper destruction of objects
> Crash fixes

- CMakeLists.txt
- cmake/modules/FindSDL2.cmake
- src/antkeymapper.cpp
- src/antkeymapper.h
- src/event.cpp
- src/eventhandlerfactory.cpp
- src/eventhandlerfactory.h
- src/eventhandlers/winsendinputeventhandler.cpp
- src/eventhandlers/winsendinputeventhandler.h
- src/eventhandlers/winvmultieventhandler.cpp
- src/eventhandlers/winvmultieventhandler.h
- src/joycontrolstick.cpp
- src/main.cpp
- src/qtwinkeymapper.cpp
- src/winextras.cpp
- src/winextras.h
Second attempt to restore Windows support based on progress made by @gombosg  and @AriaMoradi in https://github.com/AntiMicroX/antimicrox/pull/119
This PR is focused only on allowing building and launching AntiMicroX on Windows. Some features may still be disabled/broken.
Part of #4
> Restore Windows build

- README.md
- Reorder Installation instructions for packages (addresses one of changes proposed in https://github.com/AntiMicroX/antimicrox/pull/229 by @Daebis)
- Add information about udev workaround for flatpak users on wayland
Closes: #221
> Update installation instructions in readme

- src/gui/mainsettingsdialog.cpp
> fix: Missing autoprofile settings tab in Windows

- .github/workflows/main.yml
- CMakeLists.txt
- ci: add experimental clang workflow
- Add clang build as experimental
- remove parallel flag from ubuntu build, since ninja run in parallel by
default
- fix: add missing flags for clang
- disable -rdynamic for clang, not needed by clang
- add include directories for sdl2, by default it is only detecting
/usr/include
----
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>
> Add experimental support for clang

- .github/workflows/release.yml
- BUILDING.md
Follow up to https://github.com/AntiMicroX/antimicrox/pull/328
Enabling update checking for Debian builds downloaded from GitHub
> chore: Enable checking for updates for deb release builds

- other/antimicrox.1
- src/commandlineutility.cpp
- src/commandlineutility.h
- src/main.cpp
> Remove daemon mode support

- src/antimicrosettings.cpp
- src/commandlineutility.cpp
- src/commandlineutility.h
- src/gui/gamecontrollermappingdialog.cpp
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/main.cpp
- src/x11extras.cpp
- src/x11extras.h
Linked with: https://github.com/AntiMicroX/antimicrox/issues/189
> Remove unused "map" and "display" argument options with linked code

- .gitignore
- BUILDING.md
Added notes to build documentation + ignore 'builds' folder in addition to 'build' (to allow retaining of multiple builds for testing)
- build doc: add note for resolving issue with qDebug not working on custom builds (more below)
- build doc: one-liner for installing dependencies on Fedora
- gitignore: ignore 'builds' folder in addition to 'build' (allows retaining multiple builds for testing)
----
The gitignore and dependency one-liner should be fairly straight-forward so I will focus on the note for resolving qDebug output not being displayed when running custom builds. This was something I came across while doing local builds related to testing/debugging prototypes for in issue 133 [as noted here](https://github.com/AntiMicroX/antimicrox/issues/133#issuecomment-1025015871) but it was …
> BUILD.md updates + ignore 'builds' dir

- src/x11extras.cpp
Closes: https://github.com/AntiMicroX/antimicrox/issues/369  
Applies patch recommended by @Zinggi
> fix: Support obtaining bigger pid numbers from X11 windows

- src/event.cpp
- src/event.h
- src/joybutton.cpp
- src/logger.cpp
- src/logger.h
Linked with: https://github.com/AntiMicroX/antimicrox/issues/374
Main changes:
- PID of launched executables will be visible in logs
- their working directory will be in file location
> Refactor process execution

- CMakeLists.txt
Closes #378
Fixes issue introduced by https://github.com/AntiMicroX/antimicrox/pull/354
> fix: Fix wrong antimicrox icon path

- src/gui/flashbuttonwidget.cpp
- src/gui/flashbuttonwidget.h
- src/gui/mainwindow.ui
- src/joybuttonstatusbox.cpp
- src/joybuttonstatusbox.h
All child classes of FlashButtonWidget were explicitely listed in
the mainwindow's stylesheet. Hence, new child classes are not correctly
styled until they are added to the stylesheet as well.
As simplification, only add FlashButtonWidget itself to the main stylesheet
so that all child classes are automatically styled correctly.
Editing the stylesheet with QtDesigned caused the file to be
reformatted. Furthermore, remove the unused "flashed" signals.
I came across this suring implementation of #375.
> Simplify FlashButtonWidget

- src/joybutton.cpp
- src/joybutton.h
- src/joybuttonslot.cpp
- src/joybuttonslot.h
Replace it with QElapsedTimer as the deprecation warning suggests.
Remove unused function JoyButton::copyExtraAccelerationState which was
unused since it was introduced in commit f9058369.
In the JoyButtonSlot copy constructor remove the hack that copies the
time via an intermediate string and replace it with a new timer because
setting the time of a QElapsedTimer is not supported.
The new timer is started when the source timer is running.
This should not be a problems because the easingTime is usually very
small and there are not used virtual inputs while users change settings.
Fixes #318.
> Fix QTime::restart deprecation warning

- src/joybutton.cpp
In JoyButton are two switch statements which do not have cases for all
enumeration values. This causes a compiler warning.
Convert one switch to an "if" because it only has one case.
Add a default statement to the other one.
> Fix compiler warning in JoyButton

- src/applaunchhelper.cpp
- src/event.cpp
- src/gui/mainsettingsdialog.cpp
- src/gui/mousesettingsdialog.h
Do what the warnings suggest:
* Replace QDesktopWidget::screenCount() with
QGuiApplication::screens().count(). The new function returns a list of
QScreen pointers. Keep using the deprecated function
where screens are accessed by index for now.
* Replace one missed QTime with QElapsedTimer.
> Fix more easy deprecation warnings

- src/eventhandlers/uinputeventhandler.cpp
- src/eventhandlers/winsendinputeventhandler.cpp
- src/eventhandlers/xtesteventhandler.cpp
- src/joycontrolstick.cpp
- src/joydpad.cpp
QHashIterator::hasPrevious() is deprecated.
Replace most Java style iterators which use hasPrevious() with STL style
iterators and move the first iteration before the loop. According to the
Qt documentation [1], this should also be more efficient.
Keep the usage of hasPrevious() for JoyButton::slotiter since it is
used in a more sophisticated way. This is also a QListIterator where
hasPrevious is not deprecated.
[1]: https://doc.qt.io/qt-5/containers.html
> Fix QHashIterator::hasPrevious() deprecation warnings

- src/joycontrolstick.cpp
- src/joycontrolstick.h
The functions "refreshButtons" and "deleteButtons" are not used
anywhere.
> Remove dead code in JoyControlStick

- src/joybutton.cpp
Calculate mouse axis movement distance by just summing all values from
different input axes. The existing implementation with minimum and
maximum causes strange mouse "stuttering"-like movement when multiple
controller inputs are mapped to mouse movement.
This happens if both sticks are mapped as mouse and will be a major
problem with the coming sensor implementation.
> Fix mouse calculations for multiple mice

- src/gui/buttoneditdialog.cpp
- src/gui/buttoneditdialog.ui
On some systems it may happen that the ButtonEditDialog opens too small
so that is it unusable before resizing it manually. See screenshots below.
Screenshot without the change:
Screenshot with the change:
> Increase minimum size of ButtonEditDialog

- src/gui/joycontrolstickeditdialog.cpp
- src/gui/joycontrolstickeditdialog.ui
The layout of the JoySensorEditDialog jumps around when the number of
decimals in the bearing and safezone labels change.
Fix it by putting all stick labels and values from the left column in a
QGridLayout and set the length of the first value to the length of a
dummy string with nine decimals.
> Fix "jumping" JoyControlStickEditDialog layout

- CMakeLists.txt
- src/axisvaluebox.cpp
- src/gui/axiseditdialog.cpp
- src/gui/calibration.cpp
- src/gui/calibration.h
- src/gui/calibration.ui
- src/gui/joycontrolstickeditdialog.cpp
- src/gui/joycontrolstickeditdialog.ui
- src/inputdevice.cpp
- src/inputdevice.h
- src/joyaxis.cpp
- src/joyaxis.h
- src/joycontrolstick.cpp
- src/joycontrolstick.h
- src/joycontrolstickstatusbox.cpp
- src/joycontrolstickstatusbox.h
- src/pt1filter.cpp
- src/pt1filter.h
- src/statisticsestimator.cpp
- src/statisticsestimator.h
- src/xml/inputdevicexml.cpp
- src/xml/joyaxisxml.cpp
The existing axis calibration just clipped the allowed axis values to a
given maximum. Replace this with linear offset and gain calibration.
Calibration is applied when queueing pending events so that all
following calculations receive corrected values.
Replace the existing "clipping" steps with the previously uncalibrated
case - clipping to the global minimum/maximum value.
Implement an interactive calibration workflow which
automatically detects when enough data was collected by evaluation
statistic properties. The current estimated calibration values are shown
live in red and turn black if the relative error is below 1%.
If not enough values are collected after 30 seconds, time out and
continue with the available data. This avoids long calibration times
that may lead to bug reports …
> Implement offset and gain stick Calibration

- .github/workflows/main.yml
This one will have to wait some time: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
Blocked by: https://github.com/actions/virtual-environments/issues/5428
> chore: Add building with Ubuntu 22.04 to CI

- src/globalvariables.cpp
- src/globalvariables.h
- src/gui/joycontrolstickeditdialog.cpp
- src/gui/joycontrolstickeditdialog.ui
- src/joycontrolstick.cpp
- src/joycontrolstick.h
- src/joycontrolstickstatusbox.cpp
Adds a configurable threshold zone to the existing modifier key in the control stick edit dialog.
This allows mapping the analog range of a stick to walk/run in game without an extra spring button.
Closes #310
> Implement modifier button threshold zone

- src/joybuttonslot.cpp
- src/joybuttonslot.h
When button assignments are copied from one set to another, the shallow
copy of the mix slots causes a crash on exit due to the double free.
Use the already existing but commented out deep-copy code and extract a
method which is used for the copy-constructor and the assignment
operator.
Make some getters const to be able to use a const reference in the new copy function.
Fixes #454
> Deep-copy JoyButtonSlot's mix slots

- CMakeLists.txt
- src/gamecontroller/gamecontroller.cpp
- src/gamecontroller/gamecontroller.h
- src/gui/calibration.cpp
- src/inputdevice.cpp
- src/inputdevice.h
- src/inputdevicecalibration.cpp
- src/inputdevicecalibration.h
- src/joystick.cpp
- src/joystick.h
- src/xml/inputdevicexml.cpp
When you have a game console with multiple controllers and grab a random controller
every time you use it with AntimicroX, there is a good chance that the calibration
values are now incorrect since it is another physical device.
Thus, implement an internal calibration storage backend which stores calibration values for multiple controllers
and apply the correct calibration value for the current controller on load.
To distinguish multiple identical controllers types, e.g. Nintendo Switch controllers, while they are not connected simultaneously,
append the device serial number to the unique ID string.
> Allow storing calibration for multiple controllers in a profile

- src/gui/mainsettingsdialog.cpp
This bug was created during restoration of Windows support
Closes: https://github.com/AntiMicroX/antimicrox/issues/421
> fix: Broken auto profile saving for Windows

- CMakeLists.txt
- src/gamecontroller/gamecontroller.cpp
- src/gamecontroller/gamecontroller.h
- src/gamecontroller/gamecontrollerset.cpp
- src/gamecontroller/gamecontrollerset.h
- src/gamecontroller/gamecontrollertrigger.cpp
- src/gamecontroller/gamecontrollertrigger.h
- src/globalvariables.cpp
- src/globalvariables.h
- src/gui/axiseditdialog.cpp
- src/gui/axiseditdialog.h
- src/gui/axiseditdialog.ui
- src/haptictriggermodeps5.h
- src/haptictriggerps5.cpp
- src/haptictriggerps5.h
- src/inputdevice.cpp
- src/inputdevice.h
- src/joyaxis.cpp
- src/joyaxis.h
- src/xml/joyaxisxml.cpp
Add support for DualSense trigger haptic feedback if SDL version is greater or equal to 2.0.16.
There are two supported effects, click and rigid which can be configured the the axis edit dialog
if a DualSense controller is connected. The feedback point follows the trigger point, i.e. the configured dead-zone.
In preparation of this change, remove some dead XML related code and clean-up the axis edit dialog.
> Add support for DualSense trigger haptic feedback

- src/gamecontroller/gamecontrollertrigger.cpp
- src/globalvariables.cpp
- src/globalvariables.h
- src/haptictriggerps5.cpp
The click and vibration effect start/end points did not optimally match
the trigger point of the axis.
Adjust the formulas to improve it.
> Improve trigger effect exactness.

- src/joybutton.cpp
Closes: https://github.com/AntiMicroX/antimicrox/issues/436
> Fix for not refreshing labels after changing to NONE

- src/gamecontroller/gamecontroller.cpp
- src/gamecontroller/gamecontroller.h
- src/inputdevice.cpp
- src/inputdevice.h
- src/joystick.cpp
- src/joystick.h
It caused showing too many unused buttons for gamepads
Discovered thank to comment: https://github.com/AntiMicroX/antimicrox/issues/307#issue-1070082847 pointing at 21 unused buttons on gamepad
> fix: Remove hardcoded values for Gamepad class

- src/eventhandlers/uinputeventhandler.cpp
- src/gui/advancebuttondialog.cpp
- src/inputdevice.cpp
- src/joybutton.cpp
- src/joycontrolstick.cpp
- src/joydpad.cpp
- src/mousedialog/springmoderegionpreview.cpp
- src/x11extras.cpp
- src/xml/joybuttonslotxml.cpp
Closes #557 
- Fixed warnings and problems detected by Infer code analysis
> Fixing wanings by Infer code analysis #557

- src/gui/addeditautoprofiledialog.cpp
- src/inputdaemon.cpp
- src/logger.cpp
- src/main.cpp
- src/xml/inputdevicexml.cpp
- src/xml/inputdevicexml.h
- src/xmlconfigreader.cpp
- src/xmlconfigreader.h
Closes: https://github.com/AntiMicroX/antimicrox/issues/238   
Closes: https://github.com/AntiMicroX/antimicrox/issues/274
Some cleanups and fix improving execution of config reading.   
It should help with warnings:
`WARN	QObject: Cannot create children for a parent that is in a different thread`
And other related problems
> Thread fixes

- src/gui/joytabwidgetcontainer.cpp
> fix: Use proper theme-based color for tab text

- src/haptictriggerps5.cpp
- Failed to build on Fedora s390x arch, because it's big-endian - PR fixes constant as defined in glibc [`endian.h`](https://sourceware.org/git/?p=glibc.git;a=blob;f=string/endian.h;h=f91984686103d71b5bf499077d8eac4a0e0184c6;hb=HEAD#l28)
(No need for a new release just for this, I'm adding a package patch until then.)
----
> Fix __BIG_ENDIAN constant

- src/gui/mainsettingsdialog.cpp
It may cause not expected window minimalization of window on Gnome based DE https://github.com/keepassxreboot/keepassxc/issues/3333
> chore: change default setting for MinimizeToTaskbar

- src/main.cpp
In case of Windows builds we may lose several first logs, the ones containing system config are among them. To mitigate this problem I added printing second logs second time. (regular sleep on main thread to tel logger initialize did not help)
> fix: Print system config in logs second time for Windows

- src/joystick.cpp
Closes #632
This is enough of a fix to resolve the issue in #632, but there are a few other edge cases that investigation brought up that may cause a similar issue in the future.
`Joystick` was using calls to `SDK_GameController(*)` functions. On Windows 11 at least, the `SDK_Controller*` returned from `SDL_GameControllerOpen` in `Joystick`'s constructor was null, causing the unique ID building to be quite sparse. Thus, the Joystick's guid would match it's unique ID, causing profiles to fail to load automatically on startup. These changes resolve that, though some other oddities outlined in my comment in #632 do still persist.
> fix: Replace SDL controller calls with joystick ones in `Joystick`.

- BUILDING.md
- CMakeLists.txt
- src/eventhandlers/winsendinputeventhandler.cpp
- src/inputdaemon.cpp
Just two small changes and some `CMakeLists.txt` additions is all it took to build through Visual Studio 2022.
C&C welcome!
- Initializes a "potentially uninitialized" pointer that msvc whines about due to `/sdl`.
- Replaces a VLA with a `QVarLengthArray` since msvc doesn't support all of C99.
- Adds a check for msvc to `CMakeLists.txt`, and sets compiler flags that closely match the existing gcc/clang counterparts.
- Adds a few lines to `BUILDING.md` to elaborate on how to use Visual Studio's built-in cmake support to compile the project.
----
A screenshot quite unlikely needed for this, but I took one anyways 😂
Fixes the msvc warning as error due to `/sdl`.Fixes the msvc warning as error due to `/sdl`.Fixes the msvc warning as error due to `/sdl`.Fixes the msvc warning as error due to …
> chore(msvc): add msvc cmake support

- src/gui/joytabwidget.cpp
- src/joybuttonslot.cpp
```
In file included from /home/runner/work/antimicrox/antimicrox/src/gui/joytabwidget.cpp:19:
/home/runner/work/antimicrox/antimicrox/src/gui/joytabwidget.h: In constructor ‘JoyTabWidget::JoyTabWidget(InputDevice*, AntiMicroSettings*, QWidget*)’:
/home/runner/work/antimicrox/antimicrox/src/gui/joytabwidget.h:227:24: warning: ‘JoyTabWidget::tabHelper’ will be initialized after [-Wreorder]
227 |     JoyTabWidgetHelper tabHelper;
|                        ^~~~~~~~~
/home/runner/work/antimicrox/antimicrox/src/gui/joytabwidget.h:219:18: warning:   ‘InputDevice* JoyTabWidget::m_joystick’ [-Wreorder]
219 |     InputDevice *m_joystick;
|                  ^~~~~~~~~~
/home/runner/work/antimicrox/antimicrox/src/gui/joytabwidget.cpp:72:1: warning:   when initialized here [-Wreorder]
72 | …
```
> refactor: Fix reorder compile warning

- src/uinputhelper.cpp
Super_L is honored as KEY_LEFTMETA in GUI environments. (keycode 125)
Issue #749 
Closes #749
> fix: Super_L virtual keyboard map to KEY_LEFTMETA

- .github/workflows/main.yml
- .github/workflows/release.yml
18.04 Is deprecated now and GitHub runners are disabled
LInked issue https://github.com/actions/runner-images/issues/6002
> chore: Switch building AppImage build to Ubuntu 20.04

- src/inputdevice.h
Closes: https://github.com/AntiMicroX/antimicrox/issues/788
> fix: Change sdl version macro to match version od introduction

- .github/workflows/main.yml
- .github/workflows/release.yml
Bump SDL version  to the latest one (2.28.2) https://github.com/libsdl-org/SDL/releases/tag/release-2.28.2
> chore: bump SDL version to 2.28.2

- src/applaunchhelper.cpp
- src/event.cpp
- src/gui/mainsettingsdialog.cpp
- src/main.cpp
- src/mousedialog/springmoderegionpreview.cpp
- src/mousehelper.cpp
- src/mousehelper.h
- src/springmousemoveinfo.h
Linked with: #446 
Rewrite code which used QDesktopWidget Class, because it is deprecated [link](https://doc.qt.io/qt-6/widgets-changes-qt6.html#qdesktopwidget-and-qapplication-desktop)
> Rewrite code using QDesktopWidget Class

- other/io.github.antimicrox.antimicrox.desktop
This keeps the window attached to a pinned launcher, preventing things like this:
> Set StartupWMClass in Linux desktop launcher.

- src/gui/addeditautoprofiledialog.cpp
- src/gui/buttoneditdialog.cpp
The code does not compile when building with `X11=OFF`: 
```
cd antimicrox
mkdir build && cd build
cmake -DWITH_X11=OFF ..  # Fails!
cmake --build .
```
There are errors in two files that cause this.
* In `src/gui/addeditautoprofiledialog.cpp`, the code attempts to call functions of `dialog` that are not present.
* In `src/gui/buttoneditdialog.cpp`, there are two variables that have already been defined, which causes the compilation to fail.
This PR makes the code compile again.
> fix: Fixing builds with X11=OFF

- src/autoprofilewatcher.cpp
- src/common.cpp
- src/gamecontroller/gamecontroller.cpp
- src/globalvariables.cpp
- src/globalvariables.h
- src/joybuttonmousehelper.cpp
- src/joystick.cpp
- src/sdleventreader.cpp
Refactors linked with QT6 transition #446
> Chore: Refactors

- src/qtuinputkeymapper.cpp
- src/xmlconfigmigration.cpp
`QChar.unicode()` returns type: `char16_t`
https://doc.qt.io/qt-6/qchar.html#unicode
> chore: Ensure proper type for storing unicode

- src/joyaccelerometersensor.cpp
I've noticed an issue when pitching forward or backward. I expect only the "up" or "down" directions to be registered, but instead, "left" and/or "right" are also triggered for a brief period.
The SENSOR_CENTERED is 0, so at the end we just return 0 if button not yet triggered while we change direction, otherwise it can crash as it's a non-void function.
Anyway that's what I use for a week and it works for me.
> make accelerometer stable

- src/joyaccelerometersensor.cpp
Closes #991. When we change sets, both roll and pitch become NaN. We avoid comparing NaN values with numbers that in turn can trigger or not depending on compiler.
> rest accel. while changing set, fix #991

- src/eventhandlers/uinputeventhandler.cpp
- The binding labeled ‘Wheel Left’ in the GUI corresponds to mouse button 6, as seen in `src/joybuttonslot.h`. This should send a negative `REL_HWHEEL` event to uinput.
- Ditto for ‘Wheel Right’, button 7, positive `REL_HWHEEL`
----
> fix: button 6 is wheel left; button 7 is wheel right

- src/joybuttontypes/joygradientbutton.cpp
Closes #1024
- Update the `wheelEventHorizontal` code to mirror what `wheelEventVertical` does, substituting ‘horizontal’ for ‘vertical’, etc. I don't have a firm understanding of this code but it fixes the very fast horizontal wheel issue.
> fix: update wheelEventHorizontal code to match wheelEventVertical

- .github/workflows/release.yml
- BUILDING.md
- CMakeLists.txt
Closes: https://github.com/AntiMicroX/antimicrox/issues/1031
> Cleanup in deb dependencies, use QT6 in Ubuntu 24.04 build

- other/io.github.antimicrox.antimicrox.desktop
- src/main.cpp
In a Wayland session the window appId defaults to the name of the binary (`antimicrox`). This does not match the name of the .desktop launcher, so freedesktop-compliant compositors don't correctly associate the windows with the launcher. This corrects that behavior.
> wayland: Fix appId

- .github/pull_request_template.md
This fixes a typo in the instructions comment in the pull request template.
> docs: fix typo in pull request template

- other/appdata/io.github.antimicrox.antimicrox.appdata.xml.in
These changes fix displaying AntiMicroX from Flathub in GNOME Software on Debian 12.
- Fix spelling of SDL2
- Fix description formatting (paragraph split on multiple lines, line breaks in features list)
- List mouse/keyboard as supported ([see spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-relations-control)).
The AntiMicroX Flatpak builds and installs with these changes. Though it doesn't override the description in GNOME Software so it's not possible to fully confirm the result.
----
Screenshots of the current behavior:
> Update Linux appstream metadata

- src/gui/joystickstatuswindow.cpp
- src/gui/joystickstatuswindow.h
Avoid updating the accelerometer or gyroscope values if the window is closed. This prevents a segfault when the window is closed for controllers with accelerometers and gyroscopes, such as DualSense controllers.
> joystickstatuswindow: don't update accel/gyro if closed
